name: Auto Generate Maps

on:
  push:
    paths:
      - 'floorplans/**/*.png'
      - 'floorplans/**/*.bounds.json'
      - 'floorplans/**/*.annotations.json'
      - '.github/workflows/update-maps.yml'
      - 'generateMaps.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🟩 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm install sharp

      - name: 🧠 Run generateMaps.js
        run: node generateMaps.cjs

      - name: 🚀 Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-update maps and annotations" || echo "No changes to commit"
          git push
